### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by adtzlr** [adtzlr/trusspy#27]
# Preliminary Work
- [ ] Run tests with tox

# Tasks
- [ ] Automate publish on PyPI if a release is created
- [ ] Run tests and use codecov.io (needs preliminary tasks)
